export const ADD_ITEM = 1;
export const INC_ITEM = 2;
export const DEC_ITEM = 3;
export const DEL_ITEM = 4;
export const SET_NAV = 5; //for active nav
export const ADD_DATA = 6;
export const ADD_COLLECTIVE_FOODITEMS = 7;
export const ADD_COLLECTIVE_BARITEMS = 16;
export const SET_GENERAL_DATA = 8; //doesn't servers for nested data tho.
export const UPDATE_FOOD_MENU = 9;
export const UPDATE_ORDER_STATUS = 10;
export const SET_TABLE_ID = 11;
export const SET_PLACEORDER_ID = 12;
export const UPDATE_SUCCESS_ORDER = 13;
export const UPDATE_TABLE_USERS = 25;
export const REFRESH_ORDER_CLOUD = 22;
export const UPDATE_TABLE_ORDER = 14;
export const UPDATE_TABLE_NAME = 20;
export const ADD_SELECT_DATA = 17;
export const UPDATE_HOME_ITEMS = 15;
export const RESET_CART = 21;
