/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:666dc762-83d2-44e7-bd5f-f7fd945064b8",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_v9uz3gNH6",
    "aws_user_pools_web_client_id": "2oauo7q0odvn3c99dsevmstk54",
    "oauth": {}
};


export default awsmobile;
